application: stashboard
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /css
  static_dir: stashboard/static/css
  expiration: 90d

- url: /images
  static_dir: stashboard/static/images
  expiration: 90d

- url: /js
  static_dir: stashboard/static/js
  expiration: 90d
  
- url: /widget
  static_dir: stashboard/static/widget

- url: /favicon\.ico
  static_files: stashboard/static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: stashboard/static/robots.txt
  upload: static/robots.txt
  
- url: /admin.*
  script: admin.py
  secure: always
  login: admin

- url: /api.*
  script: api.py
  secure: optional

- url: .*
  script: main.py

skip_files: |
 ^(.*/)?(
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 (.*\.markdown)|
 (license\.txt)|
 (setup.py)
 )$